import type { Product } from '../../types/product'

export const mockProducts: Product[] = [
	{
		id: 1,
		title: 'iPhone 15 Pro',
		brand: 'Apple',
		category: 'Смартфоны',
		price: 119990,
		imageUrl: 'https://placehold.co/400x300?text=iPhone+15+Pro',
		description:
			'Флагманский смартфон Apple с мощным процессором, качественной камерой и премиальным корпусом.',
		rating: 4.9,
		stock: 12,
		specs: [
			{ label: 'Экран', value: '6.1 дюйма OLED' },
			{ label: 'Память', value: '256 ГБ' },
			{ label: 'Камера', value: '48 Мп' },
			{ label: 'Процессор', value: 'A17 Pro' },
		],
	},
	{
		id: 2,
		title: 'Samsung Galaxy S24',
		brand: 'Samsung',
		category: 'Смартфоны',
		price: 94990,
		imageUrl: 'https://placehold.co/400x300?text=Galaxy+S24',
		description:
			'Смартфон Samsung с ярким дисплеем, высокой производительностью и поддержкой современных AI-функций.',
		rating: 4.8,
		stock: 18,
		specs: [
			{ label: 'Экран', value: '6.2 дюйма AMOLED' },
			{ label: 'Память', value: '256 ГБ' },
			{ label: 'Камера', value: '50 Мп' },
			{ label: 'Аккумулятор', value: '4000 мА·ч' },
		],
	},
	{
		id: 3,
		title: 'Xiaomi 14',
		brand: 'Xiaomi',
		category: 'Смартфоны',
		price: 69990,
		imageUrl: 'https://placehold.co/400x300?text=Xiaomi+14',
		description:
			'Производительный смартфон с быстрой зарядкой, хорошей автономностью и качественным экраном.',
		rating: 4.7,
		stock: 24,
		specs: [
			{ label: 'Экран', value: '6.36 дюйма AMOLED' },
			{ label: 'Память', value: '512 ГБ' },
			{ label: 'Камера', value: '50 Мп' },
			{ label: 'Зарядка', value: '90 Вт' },
		],
	},
	{
		id: 4,
		title: 'Google Pixel 8',
		brand: 'Google',
		category: 'Смартфоны',
		price: 79990,
		imageUrl: 'https://placehold.co/400x300?text=Pixel+8',
		description:
			'Смартфон Google с чистым Android, сильными возможностями камеры и длительной поддержкой обновлений.',
		rating: 4.6,
		stock: 9,
		specs: [
			{ label: 'Экран', value: '6.2 дюйма OLED' },
			{ label: 'Память', value: '128 ГБ' },
			{ label: 'Камера', value: '50 Мп' },
			{ label: 'ОС', value: 'Android' },
		],
	},
	{
		id: 5,
		title: 'OnePlus 12',
		brand: 'OnePlus',
		category: 'Смартфоны',
		price: 84990,
		imageUrl: 'https://placehold.co/400x300?text=OnePlus+12',
		description:
			'Производительный смартфон с ярким экраном, быстрой зарядкой и большим объемом памяти.',
		rating: 4.7,
		stock: 14,
		specs: [
			{ label: 'Экран', value: '6.82 дюйма AMOLED' },
			{ label: 'Память', value: '256 ГБ' },
			{ label: 'Камера', value: '50 Мп' },
			{ label: 'Зарядка', value: '100 Вт' },
		],
	},
	{
		id: 6,
		title: 'Honor 90',
		brand: 'Honor',
		category: 'Смартфоны',
		price: 39990,
		imageUrl: 'https://placehold.co/400x300?text=Honor+90',
		description:
			'Смартфон среднего сегмента с большим экраном, хорошей камерой и тонким корпусом.',
		rating: 4.5,
		stock: 21,
		specs: [
			{ label: 'Экран', value: '6.7 дюйма AMOLED' },
			{ label: 'Память', value: '256 ГБ' },
			{ label: 'Камера', value: '200 Мп' },
			{ label: 'Аккумулятор', value: '5000 мА·ч' },
		],
	},
	{
		id: 7,
		title: 'Samsung Galaxy A55',
		brand: 'Samsung',
		category: 'Смартфоны',
		price: 44990,
		imageUrl: 'https://placehold.co/400x300?text=Galaxy+A55',
		description:
			'Сбалансированный смартфон Samsung с хорошим дисплеем и защитой корпуса.',
		rating: 4.6,
		stock: 30,
		specs: [
			{ label: 'Экран', value: '6.6 дюйма Super AMOLED' },
			{ label: 'Память', value: '128 ГБ' },
			{ label: 'Камера', value: '50 Мп' },
			{ label: 'Защита', value: 'IP67' },
		],
	},
	{
		id: 8,
		title: 'iPhone 14',
		brand: 'Apple',
		category: 'Смартфоны',
		price: 79990,
		imageUrl: 'https://placehold.co/400x300?text=iPhone+14',
		description:
			'Смартфон Apple предыдущего поколения с надежной производительностью и качественным экраном.',
		rating: 4.6,
		stock: 16,
		specs: [
			{ label: 'Экран', value: '6.1 дюйма OLED' },
			{ label: 'Память', value: '128 ГБ' },
			{ label: 'Камера', value: '12 Мп' },
			{ label: 'Процессор', value: 'A15 Bionic' },
		],
	},
	{
		id: 9,
		title: 'Xiaomi Redmi Note 13',
		brand: 'Xiaomi',
		category: 'Смартфоны',
		price: 24990,
		imageUrl: 'https://placehold.co/400x300?text=Redmi+Note+13',
		description:
			'Доступный смартфон с большим экраном, емким аккумулятором и хорошей автономностью.',
		rating: 4.4,
		stock: 42,
		specs: [
			{ label: 'Экран', value: '6.67 дюйма AMOLED' },
			{ label: 'Память', value: '128 ГБ' },
			{ label: 'Камера', value: '108 Мп' },
			{ label: 'Аккумулятор', value: '5000 мА·ч' },
		],
	},
	{
		id: 10,
		title: 'Google Pixel 7a',
		brand: 'Google',
		category: 'Смартфоны',
		price: 49990,
		imageUrl: 'https://placehold.co/400x300?text=Pixel+7a',
		description:
			'Компактный смартфон Google с чистым Android и хорошими возможностями камеры.',
		rating: 4.5,
		stock: 11,
		specs: [
			{ label: 'Экран', value: '6.1 дюйма OLED' },
			{ label: 'Память', value: '128 ГБ' },
			{ label: 'Камера', value: '64 Мп' },
			{ label: 'ОС', value: 'Android' },
		],
	},
	{
		id: 11,
		title: 'Nothing Phone 2',
		brand: 'Nothing',
		category: 'Смартфоны',
		price: 69990,
		imageUrl: 'https://placehold.co/400x300?text=Nothing+Phone+2',
		description:
			'Смартфон с необычным дизайном корпуса, ярким экраном и чистым интерфейсом.',
		rating: 4.5,
		stock: 8,
		specs: [
			{ label: 'Экран', value: '6.7 дюйма OLED' },
			{ label: 'Память', value: '256 ГБ' },
			{ label: 'Камера', value: '50 Мп' },
			{ label: 'Особенность', value: 'Glyph Interface' },
		],
	},
	{
		id: 12,
		title: 'Huawei P60 Pro',
		brand: 'Huawei',
		category: 'Смартфоны',
		price: 89990,
		imageUrl: 'https://placehold.co/400x300?text=Huawei+P60+Pro',
		description:
			'Флагманский смартфон Huawei с акцентом на камеру, дизайн и автономность.',
		rating: 4.6,
		stock: 7,
		specs: [
			{ label: 'Экран', value: '6.67 дюйма OLED' },
			{ label: 'Память', value: '256 ГБ' },
			{ label: 'Камера', value: '48 Мп' },
			{ label: 'Аккумулятор', value: '4815 мА·ч' },
		],
	},
]
